# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('imgurl', models.TextField(max_length=100)),
                ('imgherf', models.TextField(max_length=100)),
                ('imgvisit', models.TextField(max_length=20)),
                ('imglike', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'huaban',
            },
        ),
        migrations.DeleteModel(
            name='Guojia',
        ),
    ]
